name: generate monkeytype readme svg

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download SVG
        run: |
          mkdir public
            curl -o public/monkeytype-readme.svg https://monkeytype-readme.com/generate-svg/ChouCho_P/shadow
            curl -o public/monkeytype-readme-lb.svg https://monkeytype-readme.com/generate-svg/ChouCho_P/shadow?lb=true
            curl -o public/monkeytype-readme-pb.svg https://monkeytype-readme.com/generate-svg/ChouCho_P/shadow?pb=true
            curl -o public/monkeytype-readme-lb-pb.svg https://monkeytype-readme.com/generate-svg/ChouCho_P/shadow?lbpb=true
      - name: Push monkeytype-readme.svg to the monkeytype-readme branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: monkeytype-readme
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
